# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        ndk_version: [20.1.5948944]
        os: [windows-latest,ubuntu-latest,macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      
      - name: Bootstrap
        run: ./bootstrap-vcpkg.sh
        if: ${{ matrix.os != "windows-latest" }}
        
      - name: Bootstrap (Windows)
        run: ./bootstrap-vcpkg.bat
        if: ${{ matrix.os == "windows-latest" }}

